/// generated by batch_nodetypes.js
module.exports = {
  "dict_a": [
    "NOP",
    "LET",
    "VALUE",
    "PRINT",
    "NUM",
    "STR",
    "FUNC",
    "OP",
    "BLOCK"
  ],
  "NOP": 0,
  "LET": 1,
  "VALUE": 2,
  "PRINT": 3,
  "NUM": 4,
  "STR": 5,
  "FUNC": 6,
  "OP": 7,
  "BLOCK": 8
};