#!/usr/bin/env node

// converter : nodetypes.txt => nodetypes.js
const target = __dirname + '/nodetypes.txt';
const saveto = __dirname + '/nodetypes.js';

// read
const fs = require('fs');
const data = fs.readFileSync(target, "utf-8");

// convert
const words = [];
const lines = data.split(/[\,\n]/);
lines.forEach( (line) => {
  line = line.replace(/\s+/g, '');
  if (line == '' || line.charAt(0) == '#') return;
  words.push(line);
});

// make object
const xpt = {};
xpt.dict_a = [];
for (let id = 0; id < words.length; id++) {
  const w = words[id];
  xpt[w] = id;
  xpt.dict_a.push(w);
}

// output
const res = "/// generated by batch_nodetypes.js\n" +
  "module.exports = " + JSON.stringify(xpt,null,2) + ";";
// output
fs.writeFileSync(saveto, res, "utf-8");
console.log(res);

