/// generated by batch_nodetypes.js
module.exports = {
  "dict_a": [
    "NOP",
    "BLOCK",
    "EOL",
    "LET",
    "VALUE",
    "NUM",
    "STR",
    "OP",
    "FUNC",
    "REF_VAR",
    "REF_VAR_LOCAL",
    "PRINT"
  ],
  "NOP": 0,
  "BLOCK": 1,
  "EOL": 2,
  "LET": 3,
  "VALUE": 4,
  "NUM": 5,
  "STR": 6,
  "OP": 7,
  "FUNC": 8,
  "REF_VAR": 9,
  "REF_VAR_LOCAL": 10,
  "PRINT": 11
};